id: 609b756b8c114070884e414567cfd5ed
initial_creation_type: ocr
source_metadata:
  volumes:
    8db37d712ec446998ef21e0ca0d62181:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: ''
      total_pages: 1902
      volume_number: 64
